### ISSUE TITLE
There is a big issue with app in release mode while everything's ok in debug mode

### ISSUE THREAD

**Issue by RamiBadyan** [AppLovin/AppLovin-MAX-SDK-Android#60] opened 2021-12-03 19:14 UTC
When the app in release mode and I try to show the ad, the app crashes.
**I noticed that this happens when the ad is a video.** 
The error occurs on most devices, my app is affected by more than 23K users, and the app has crashed for more than 200K.
After that, I stopped displaying the ad. 

The issue is happening with ExoPlayer. I use the ExoPlayer library, but I do not display the ad while the video is playing,
the video player is in another activity and the ad is in another activity.

**Error message:**

Fatal Exception: java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onEvents(com.google.android.exoplayer2.Player, com.google.android.exoplayer2.Player$Events)"
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$0(ExoPlayerImpl.java:200)
       at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda16.invoke()
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:272)
       at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet.java:224)
       at com.google.android.exoplayer2.util.ListenerSet.$r8$lambda$eEvjP-IE0x3J2lRvKfFbbjRFRvc(ListenerSet.java)
       at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda0.handleMessage()
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6571)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:986)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

I hope to fix this issue.

**Comment by Lorenzo45** [comment] 2021-12-03 22:37
Hey @RamiBadyan - we've seen this crash before. It's caused by a build issue and should be fixed if you add `android.enableDexingArtifactTransform=false` to `gradle.properties`. Let us know if this works for you.

**Comment by RamiBadyan** [comment] 2021-12-15 12:59
> Hey @RamiBadyan - we've seen this crash before. It's caused by a build issue and should be fixed if you add `android.enableDexingArtifactTransform=false` to `gradle.properties`. Let us know if this works for you.

Thank you. It is works.

**Closed** 2021-12-15 12:59 UTC
