### ISSUE TITLE
Applovin increased the crash rate in my app.

### ISSUE THREAD

**Issue by Djemre0** [AppLovin/AppLovin-MAX-SDK-Android#715] opened 2024-09-20 10:02 UTC
### Feature Description

The number of crashes caused solely by Applovin in the last week.
![Ekran görüntüsü 2024-09-20 125727](https://github.com/user-attachments/assets/035ab36f-00ae-4982-b0f7-a76294b8448a)
![Ekran görüntüsü 2024-09-20 125803](https://github.com/user-attachments/assets/1756a868-65ba-424d-9e64-293d519bd5e0)
![Ekran görüntüsü 2024-09-20 125901](https://github.com/user-attachments/assets/d76c1d85-bd07-40fd-8971-89a845c2aefc)
"Crash content
![Ekran görüntüsü 2024-09-20 130124](https://github.com/user-attachments/assets/b5e6fc30-0499-4179-beb6-0881cc8ed536)

**Comment by applovinAsh** [comment] 2024-09-20 22:22
Duplicate of https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/714

**Closed by applovinAsh** 2024-09-20 22:22 UTC
Labels: enhancement
