### ISSUE TITLE
Rewarded Interstitial Ads freeze

### ISSUE THREAD

**Issue by akargapolov** [AppLovin/AppLovin-MAX-SDK-Android#703] opened 2024-08-27 09:13 UTC
### MAX SDK Version

12.6.1

### Device/Platform Info

Android 14, Pixel 8 API 33 Emulator

### Current Behavior

Start game with Mediation Debugger. Start AppLovin Rewarded Ad in test mode.
See REWARDED: onAdDisplayed event
and no events after, can't back to Debugger or game

<img width="633" alt="image" src="https://github.com/user-attachments/assets/e12423da-fe13-46ce-b0f9-112f0fcdfe34">

### How to Reproduce

Start game with Mediation Debugger. Start AppLovin Rewarded Ad in test mode

**Comment by NanaAmoah** [comment] 2024-08-27 22:38
Hi @akargapolov we released a fix for this issue. If you are still reproducing it, please send us the following to help us investigate further:

- The full Ad Report of the creative using our [Creative Debugger](https://developers.applovin.com/en/max/android/testing-networks/creative-debugger/) tool.
- Full [verbose logs](https://developers.applovin.com/en/max/android/overview/advanced-settings#enable-verbose-logging) of an app session where the issue is reproduced.

**Comment by akargapolov** [comment] 2024-08-28 04:48
Hi @NanaAmoah logs attached
[creativeDebugger.txt](https://github.com/user-attachments/files/16776442/creativeDebugger.txt)
[verbose.log](https://github.com/user-attachments/files/16776443/verbose.log)

**Comment by akargapolov** [comment] 2024-08-28 06:49
Found a problem in our app, on pause main activity webView.pauseTimers() executed.
If remove pauseTimers applovin test ad works

**Comment by NanaAmoah** [comment] 2024-08-28 16:39
Thanks for letting us know @akargapolov

**Closed** 2024-08-28 16:39 UTC
Labels: bug
