### ISSUE TITLE
Clear SharedPreferences crash - NPE

### ISSUE THREAD

**Issue by xDragonZ** [AppLovin/AppLovin-MAX-SDK-Android#534] opened 2023-08-21 15:21 UTC
### MAX SDK Version

11.11.2

### Device/Platform Info

Android 13

### Current Behavior

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at com.applovin.impl.b.b.a.onSharedPreferenceChanged(SourceFile:113)
at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:629)
at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:617)
```

### How to Reproduce

```
  SharedPreferences.Editor editor = settings.edit();
  editor.clear();
  editor.commit();
```

### Additional Info

<img width="775" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/951083/cdaf4054-0e6e-47d6-ae9b-e166abd1b49e">

**Comment by wootaejeon** [comment] 2023-08-21 19:47
Hi @xDragonZ thanks for reporting the issue. We've identified the cause of the issue and the fix will be included in our next release. Will update on this thread once the next sdk version gets pushed.

**Comment by thomasmso** [comment] 2023-08-24 19:08
Fix is live in SDK v11.11.3. Thanks for reporting it @xDragonZ.

**Closed by thomasmso** 2023-08-24 19:08 UTC
Labels: bug

**Comment by candratop3** [comment] 2023-09-04 13:04
> Fix is live in SDK v11.11.3. Thanks for reporting it @xDragonZ.

give him, more CPM bro!

**Comment by rjsuzuki** [comment] 2023-09-14 18:52
Could someone please explain what the impact of this bug was?

**Comment by IneptStudio** [comment] 2023-10-31 04:44
Hi i think there is a bug in this version in unity, I am using  unity version: 2022.3.11f1 for my game.
Bug: After installing (admob or adsense) as a mediation partner , my project is not building, and even does not work after removing both of them, Screenshots are attached.

How to Reproduce:
1.Simply create a new unity project and convert it to android 
2. install applovin sdk and enable auto resolution and enter your sdk key.
3. after that simply install admob or adsense anything you like from integration manager as our mediation partner 
  and here you go , you project will not build , i spended weeks on this thing, and i don't know what is the problem.

As it is a new fresh project that is why i think it can be due to applovin.
![error](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/82321827/2c2b7a49-9b23-4ede-9fb8-bcd95a2a1d1c)

this screenshot is from my orignal project and this same thing i got in newly fresh project also.
