### ISSUE TITLE
Exoplayer error "java.lang.AbstractMethodError"

### ISSUE THREAD

**Issue by murilobesse** [AppLovin/AppLovin-MAX-SDK-Android#85] opened 2022-01-12 17:52 UTC
Hi,
I'm migrating my apps from Mopub SDK to AppLovin.
With an example app I manage to show Intersticial test Ads, but adding the code to one of my apps I've got this error right after calling "interstitialAd.ShowAd":

> java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onEvents(com.google.android.exoplayer2.Player, com.google.android.exoplayer2.Player$Events)"
> at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$0$ExoPlayerImpl(ExoPlayerImpl.java:168)
> at com.google.android.exoplayer2.ExoPlayerImpl$$Lambda$1.invoke(Unknown Source:12)
> at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:309)
> at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet.java:253)
> at com.google.android.exoplayer2.util.ListenerSet.bridge$lambda$0$ListenerSet(Unknown Source:4)
> at com.google.android.exoplayer2.util.ListenerSet$$Lambda$0.handleMessage(Unknown Source:6)
> at android.os.Handler.dispatchMessage(Handler.java:103)
> at android.os.Looper.loop(Looper.java:225)
> at android.app.ActivityThread.main(ActivityThread.java:7564)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

This app depends on the Exoplayer library, I guess that MAX mediation depends on it too, and at some point it conflicts.

**Comment by Lorenzo45** [comment] 2022-01-12 19:47
Hi @murilobesse - We've seen this crash before. Can you try adding `android.enableDexingArtifactTransform=false` to `gradle.properties`? That should fix the crash.

**Comment by murilobesse** [comment] 2022-01-13 12:17
Yes, I've seen this solution too, but I'm using B4X and asked them how to do this.
 Here is the answer:

"_It is not possible. Based on the fact that it works when ExoPlayer isn't selected, my guess is that they depend on a different version of ExoPlayer._"

Do you know which version of ExoPlayer Max SDK depends ?

**Comment by Lorenzo45** [comment] 2022-01-14 01:35
It's not a dependency issue, the problem is that we don't have a dependency on ExoPlayer which may lead to build issues if that gradle setting I mentioned earlier is missing. If you're able to add that setting to your project somehow that would be ideal. We plan to make changes do address this but we don't have an ETA yet. At the moment your only two options are to use an older version of our SDK (10.2.0) or remove ExoPlayer from your app.

**Comment by vanniktech** [comment] 2022-03-16 09:47
@Lorenzo45 is there any update on the fix? I'm also hit by the same problem.

---

I have a mono repo where I have more than one app. Although I'm having this problem only with one particular app (the others aren't using exoplayer). Is there any way to use the workaround of setting `android.enableDexingArtifactTransform=false` only to that one particular project? Like, do I need to set it in `<root>/gradle.properties` or can I move that setting to `my-app/gradle.properties` and it'll work just as well?

**Comment by Lorenzo45** [comment] 2022-03-16 11:00
If you have an existing `gradle.properties` file you should be able to add it there. If that doesn't work we can explore alternative solutions.

**Comment by vanniktech** [comment] 2022-03-16 11:20
I do have 

- `./gradle.properties` which contains Android configurations such as jetifier, R8 full mode etc.

I'd like to apply the `android.enableDexingArtifactTransform` property only to one specific app, since only one app is using AppLovin. I guess I'll just create a:

-`my-app/gradle.properties` file with `android.enableDexingArtifactTransform=false`, publish an update and see if this fixes it. Worst case, I'll need to move it up to my root gradle.properties file

**Comment by vanniktech** [comment] 2022-03-20 08:26
@Lorenzo45 can confirm that putting `android.enableDexingArtifactTransform=false` at the root level works.

**Comment by Lorenzo45** [comment] 2022-03-22 22:20
@vanniktech We use ExoPlayer as an optional dependency. Newer versions of Gradle have a build optimization that can cause these crashes with optional dependencies (which is disabled with that setting above).

**Comment by murilobesse** [comment] 2022-03-23 11:44
> @vanniktech We use ExoPlayer as an optional dependency. Newer versions of Gradle have a build optimization that can cause these crashes with optional dependencies (which is disabled with that setting above).

Which version of exoplayer are you depending ?

**Comment by vanniktech** [comment] 2022-03-23 12:24
2.16.1 (released) although I've started upgrading to 2.17.1 (not released yet)

**Comment by vanniktech** [comment] 2022-04-01 17:51
Thanks, I'm afraid this isn't something I can use though as I have a transitive dependency on AppLovin through a different SDK.

**Comment by thomasmso** [comment] 2022-04-01 19:44
We can't control the dependencies of other SDKs. This is to control whether or not AppLovin Bidding / AppLovin Exchange video ads use ExoPlayer or not if indeed pulled in from another SDK.

**Comment by vanniktech** [comment] 2022-04-11 09:50
> @vanniktech We use ExoPlayer as an optional dependency. Newer versions of Gradle have a build optimization that can cause these crashes with optional dependencies (which is disabled with that setting above).

Is there any issue that I can track? This should be fixed on either Gradle's front or AGP's front, right?

**Comment by Lorenzo45** [comment] 2022-04-11 20:36
Sounds like this won't be fixed and is marked as intended behavior. Here are a couple threads:
https://github.com/google/ExoPlayer/issues/6801#issuecomment-579164194
https://issuetracker.google.com/issues/139821726#comment5

You may want to consider adding our SDK as a direct dependency instead of using our SDK through a different SDK. You can read more about how to do this in our docs here: https://dash.applovin.com/documentation/mediation/max/get-started-with-max

**Comment by vanniktech** [comment] 2022-04-15 12:55
From my understanding why can't apploving declare the dependency of exoplayer? That would solve all problems, right?

**Comment by Lorenzo45** [comment] 2022-04-15 20:17
We've avoided this to ensure our SDK is backwards compatible with Java 7 as ExoPlayer requires Java 8. We're considering making the change now that Java 8 has become more widely accepted though.

**Comment by vanniktech** [comment] 2022-04-15 20:54
It's safe to enforce Java 8 Feature. Some super popular libraries which will enforce this:

- AndroidX libraries 
- RxJava 2/3
- Retrofit
- java.time. desugaring

Tooling side from Android is also ready.

**Comment by Lorenzo45** [comment] 2022-05-13 07:30
Hi everyone,
We just released AppLovin SDK 11.4.0 which includes ExoPlayer as a dependency. This will resolve the crash described above.

After updating to SDK 11.4.0, ensure your project is using Java 8+ using these instructions:
https://exoplayer.dev/hello-world.html#turn-on-java-8-support

**Closed by Lorenzo45** 2022-05-13 07:30 UTC
