### ISSUE TITLE
Crash of [base.apk!libmonochrome_64.so] 

### ISSUE THREAD

**Issue by harinlin** [AppLovin/AppLovin-MAX-SDK-Android#662] opened 2024-04-27 09:20 UTC
### MAX SDK Version

12.4.2

### Device/Platform Info

Android 14 (Most)/ Android 13 /Android 12 /Android 11/Android 10

### Current Behavior

Lots of type crashes and lots of [base.apk!libmonochrome_64.so]

### Expected Behavior

There shouldn't be a lot of crashes

### How to Reproduce

[FATAL:crashpad_client_linux.cc(745)] Render process (18518)'s crash wasn't handled by all associated  webviews, triggering application crash.

backtrace:
  #00  pc 0x0000000003384668  /data/app/~~GmaDppjFDDFO1iYzddcmaQ==/com.google.android.trichromelibrary_631211833-8-6T990wxE2r7GN4dXbcVQ==/base.apk!libmonochrome_64.so (BuildId: 8fd6e95854e141c4caef495941f83858663e0788)
  #01  pc 0x000000000637bfe8  /data/app/~~GmaDppjFDDFO1iYzddcmaQ==/com.google.android.trichromelibrary_631211833-8-6T990wxE2r7GN4dXbcVQ==/base.apk!libmonochrome_64.so (BuildId: 8fd6e95854e141c4caef495941f83858663e0788)
  #02  pc 0x0000000006d81b54  /data/app/~~GmaDppjFDDFO1iYzddcmaQ==/com.google.android.trichromelibrary_631211833-8-6T990wxE2r7GN4dXbcVQ==/base.apk!libmonochrome_64.so (BuildId: 8fd6e95854e141c4caef495941f83858663e0788)
  #03  pc 0x0000000004671478  /data/app/~~GmaDppjFDDFO1iYzddcmaQ==/com.google.android.trichromelibrary_631211833-8-6T990wxE2r7GN4dXbcVQ==/base.apk!libmonochrome_64.so (BuildId: 8fd6e95854e141c4caef495941f83858663e0788)
  #04  pc 0x0000000002c95a20  /data/app/~~GmaDppjFDDFO1iYzddcmaQ==/com.google.android.trichromelibrary_631211833-8-6T990wxE2r7GN4dXbcVQ==/base.apk!libmonochrome_64.so (BuildId: 8fd6e95854e141c4caef495941f83858663e0788)
  #05  pc 0x00000000063ab4a4  /data/app/~~GmaDppjFDDFO1iYzddcmaQ==/com.google.android.trichromelibrary_631211833-8-6T990wxE2r7GN4dXbcVQ==/base.apk!libmonochrome_64.so (BuildId: 8fd6e95854e141c4caef495941f83858663e0788)
  #06  pc 0x0000000003d053e8  /data/app/~~GmaDppjFDDFO1iYzddcmaQ==/com.google.android.trichromelibrary_631211833-8-6T990wxE2r7GN4dXbcVQ==/base.apk!libmonochrome_64.so (BuildId: 8fd6e95854e141c4caef495941f83858663e0788)
  #07  pc 0x0000000000018b70  /system/lib64/libutils.so (android::Looper::pollInner(int)+1252)
  #08  pc 0x0000000000018628  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+124)
  #09  pc 0x000000000018f264  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48)
  #10  pc 0x000000000033f514  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+116)
  #11  pc 0x0000000000a2e680  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.MessageQueue.next+304)
  #12  pc 0x0000000000a2b180  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+96)
  #13  pc 0x0000000000a2b078  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+1112)
  #14  pc 0x000000000078b100  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.main+2432)
  #15  pc 0x000000000033b680  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
  #16  pc 0x000000000037cb18  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1556)
  #17  pc 0x000000000037c4f4  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32)
  #18  pc 0x00000000003456a8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+120)
  #19  pc 0x0000000000d99aa4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+132)
  #20  pc 0x0000000000da5054  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3604)
  #21  pc 0x000000000033b680  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
  #22  pc 0x00000000004e2a90  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+728)
  #23  pc 0x000000000057aa68  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+156)
  #24  pc 0x00000000000e3be8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+108)
  #25  pc 0x00000000000f05bc  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+856)
  #26  pc 0x0000000000002558  /system/bin/app_process64 (main+1280)
  #27  pc 0x0000000000053e8c  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108)

**Comment by harinlin** [comment] 2024-04-28 14:20
Here : 
1. https://issuetracker.google.com/issues/325120865#comment1
2. https://issuetracker.google.com/issues/324276401

Please fix it as soon as possible, please!!!
@thomasmso @thomasmso

**Comment by harinlin** [comment] 2024-05-01 04:55
any response??
As a commercial SDK, it has no responsibility to respond to users’ questions?

WTF !!!!!!!

**Comment by cemtuver-applovin** [comment] 2024-05-01 12:11
Hey @harinlin! The crash traces of the Android WebView do not provide sufficient information to determine the exact cause of the crashing WebView. Therefore, it is difficult to identify which WebView is causing the issue. In order to investigate this further, could you please provide me with the following details:
- Do you use any other ad network SDK or adapter? If yes, please share the adapters you use and their versions.
- Do you have any custom tracking events or information available on Firebase that could help identify the crashing WebView?
- Can you reproduce this crash? If so, would you be able to share with me a debuggable APK and the steps to reproduce it?

**Comment by harinlin** [comment] 2024-05-01 16:07
> Hey @harinlin! The crash traces of the Android WebView do not provide sufficient information to determine the exact cause of the crashing WebView. Therefore, it is difficult to identify which WebView is causing the issue. In order to investigate this further, could you please provide me with the following details:
> 
> * Do you use any other ad network SDK or adapter? If yes, please share the adapters you use and their versions.
> * Do you have any custom tracking events or information available on Firebase that could help identify the crashing WebView?
> * Can you reproduce this crash? If so, would you be able to share with me a debuggable APK and the steps to reproduce it?

Hi @cemtuver-applovin , our app do nothing but just upgrade applovin version and network adapter(all network are applovin offical sdk), after that, the crash increase a lot.
Now we have downgrade to 12.1.0 and all network adapter before 2024.2.1， this crash gone!!
And we notice some app, such as : [PaintByNumber](https://play.google.com/store/apps/details?id=paint.by.number.pixel.art.coloring.drawing.puzzle),  [Art Puzzle](https://play.google.com/store/apps/details?id=art.puzzle.games.jigsaw.coloring.free.game), they upgrade their apps, and downgrade applovin sdk to 12.1.0!!!
We do not find the reproduce way, sorry for that.  
Now we can dont is downgrade to version 12.1.0

**Comment by cemtuver-applovin** [comment] 2024-05-01 21:10
Hi @harinlin. Thanks for your reply! Could you please also share the versions of your AppLovin adapters? I am particularly interested in knowing which ad networks (adapters) you had integrated and what their versions were when the crash rate increased. Please also let me know which versions you downgraded them to.

**Comment by harinlin** [comment] 2024-05-02 10:34
@cemtuver-applovin After we compared two different versions of our app,upgrade applovin  and ads network sdk versions, we also introduced the biddingmachine sdk. 
A full-text search of the biddingmachine sdk found that it does not override onRenderProcessGone. 
Could you please help to troubleshoot whether the problem is caused by biddingmachine sdk?
![screenshot-20240502-182444](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/4169326/f0b78a50-faba-4203-a3f3-802c7034a9d0)
![20240502-182825](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/4169326/5076b42b-582b-4428-945d-20edb3b56fd4)

**Comment by cemtuver-applovin** [comment] 2024-05-02 13:40
@harinlin BidMachine stated that they have fixed this issue since their SDK version 2.5.1, as per their [changelogs](https://docs.bidmachine.io/docs/android-changelog#version-251-march-1-2024). Do you know if you had an earlier version integrated when the crash rate increased?

**Comment by harinlin** [comment] 2024-05-02 14:41
checked:  BidingMachine network integrated  version : 2.6.0.1, the lastest version.
i will remove biding machine network, and retest later

**Comment by cemtuver-applovin** [comment] 2024-05-03 08:15
@harinlin thank you for testing. Please do let me know the results.

**Comment by harinlin** [comment] 2024-05-15 07:52
@cemtuver-applovin after test, we find the cause sdk is : Smatto. After remove Smatto, 12.4.2 also works well

**Comment by cemtuver-applovin** [comment] 2024-05-15 08:16
Hi @harinlin, thank you for your time and testing. Could you also report this issue directly to Smaato? I'll close the issue, but feel free to reopen if you find further problems.

**Closed by cemtuver-applovin** 2024-05-15 08:16 UTC
Labels: bug
