### ISSUE TITLE
PangleWebView crash on 12.6.1

### ISSUE THREAD

**Issue by stdlam** [AppLovin/AppLovin-MAX-SDK-Android#710] opened 2024-09-13 07:06 UTC
### MAX SDK Version

12.6.1

### Device/Platform Info

Android

### Crashes/ANRs per Day

every time to load native ads

### Percentage of Users Affected

100%

### First Occurrence of Crash/ANR

Maybe after updating from an older SDK version.

### Exception and Stack Trace

java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'AppLovinSdk:shared_thread_pool'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {4f6fe91} called on null, FYI main Looper is Looper (main, tid 2) {4f6fe91})
                                                                                                    	at android.webkit.WebView.checkThread(WebView.java:2630)
                                                                                                    	at android.webkit.WebView.removeJavascriptInterface(WebView.java:1943)
                                                                                                    	at com.bytedance.sdk.component.widget.PangleWebView.removeJavascriptInterface(PangleWebView.java:81)
                                                                                                    	at com.bytedance.sdk.openadsdk.gQ.NlF.lFD(LandingPageLog.java:565)
                                                                                                    	at com.bytedance.sdk.openadsdk.core.nativeexpress.Zdu.ErO(WebViewRender.java:312)
                                                                                                    	at com.bytedance.sdk.component.adexpress.gQ.ho.OXt(WebViewRenderInterceptor.java:75)
                                                                                                    	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.NlF(NativeExpressView.java:997)
                                                                                                    	at com.bytedance.sdk.openadsdk.core.bannerexpress.BannerExpressView.lFD(BannerExpressView.java:186)
                                                                                                    	at com.bytedance.sdk.openadsdk.core.bannerexpress.OXt.destroy(PAGBannerAdImpl.java:184)
                                                                                                    	at com.applovin.mediation.adapters.ByteDanceMediationAdapter.onDestroy(ByteDanceMediationAdapter.java:274)
                                                                                                    	at com.applovin.impl.mediation.g.l(SourceFile:3)
                                                                                                    	at com.applovin.impl.mediation.g.$r8$lambda$M0-41Qz0EJAwuzvMp176QgZnzQA(Unknown Source:0)
                                                                                                    	at com.applovin.impl.mediation.g$$ExternalSyntheticLambda11.run(D8$$SyntheticClass:0)
                                                                                                    	at com.applovin.impl.mediation.g.a(SourceFile:5870)
                                                                                                    	at com.applovin.impl.mediation.g.$r8$lambda$Bzit5t9eqfA6lP9x96YlsSo49TU(Unknown Source:0)
                                                                                                    	at com.applovin.impl.mediation.g$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at com.applovin.impl.jn.run(SourceFile:46)
                                                                                                    	at com.applovin.impl.tm$d.run(SourceFile:24)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.Throwable: A WebView method was called on thread 'AppLovinSdk:shared_thread_pool'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {4f6fe91} called on null, FYI main Looper is Looper (main, tid 2) {4f6fe91})
                                                                                                    	at android.webkit.WebView.checkThread(WebView.java:2625)
                                                                                                    	at android.webkit.WebView.removeJavascriptInterface(WebView.java:1943) 
                                                                                                    	at com.bytedance.sdk.component.widget.PangleWebView.removeJavascriptInterface(PangleWebView.java:81) 
                                                                                                    	at com.bytedance.sdk.openadsdk.gQ.NlF.lFD(LandingPageLog.java:565) 
                                                                                                    	at com.bytedance.sdk.openadsdk.core.nativeexpress.Zdu.ErO(WebViewRender.java:312) 
                                                                                                    	at com.bytedance.sdk.component.adexpress.gQ.ho.OXt(WebViewRenderInterceptor.java:75) 
                                                                                                    	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.NlF(NativeExpressView.java:997) 
                                                                                                    	at com.bytedance.sdk.openadsdk.core.bannerexpress.BannerExpressView.lFD(BannerExpressView.java:186) 
                                                                                                    	at com.bytedance.sdk.openadsdk.core.bannerexpress.OXt.destroy(PAGBannerAdImpl.java:184) 
                                                                                                    	at com.applovin.mediation.adapters.ByteDanceMediationAdapter.onDestroy(ByteDanceMediationAdapter.java:274) 
                                                                                                    	at com.applovin.impl.mediation.g.l(SourceFile:3) 
                                                                                                    	at com.applovin.impl.mediation.g.$r8$lambda$M0-41Qz0EJAwuzvMp176QgZnzQA(Unknown Source:0) 
                                                                                                    	at com.applovin.impl.mediation.g$$ExternalSyntheticLambda11.run(D8$$SyntheticClass:0) 
                                                                                                    	at com.applovin.impl.mediation.g.a(SourceFile:5870) 
                                                                                                    	at com.applovin.impl.mediation.g.$r8$lambda$Bzit5t9eqfA6lP9x96YlsSo49TU(Unknown Source:0) 
                                                                                                    	at com.applovin.impl.mediation.g$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                    	at com.applovin.impl.jn.run(SourceFile:46) 
                                                                                                    	at com.applovin.impl.tm$d.run(SourceFile:24) 
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)

### How to Reproduce

Just open AppLovin native ads

### Reproducible in the demo app?

Yes

**Comment by NanaAmoah** [comment] 2024-09-16 16:28
Hi @stdlam I am not able to reproduce the issue on our demo app on v12.6.1 of the AppLovin SDK. Can you clarify the following:

- Are you able to reproduce this with v13.0.0 of the AppLovin SDK?
- What Pangle adapter version are you on? 
- Since you were able to reproduce this in our demo app 100% of the time, you share the project with me?

**Comment by NanaAmoah** [comment] 2024-11-20 21:21
Hi @stdlam, we've released a fix for this issue in v13.0.1 of the AppLovin SDK.

**Closed by NanaAmoah** 2024-11-20 21:21 UTC
Labels: bug
